---

- name: awscliv2 dl.
  ansible.builtin.shell:
    cmd: |
      curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip \
      -o /tmp/awscliv2.zip
    # environment:
    #   http_proxy: "{{ proxy_value }}"
    #   https_proxy: "{{ proxy_value }}"

- name: awscliv2.zip unzip.
  ansible.builtin.unarchive:
    src: "/tmp/awscliv2.zip"
    dest: /tmp/

- name: awscliv2 install.
  ansible.builtin.shell: "sudo /tmp/aws/install --update"

- name: awscliv2 resource remove.
  ansible.builtin.shell: "rm -rf /tmp/awscliv2.zip && rm -rf /tmp/aws"
